name: update-app

on:
  workflow_dispatch:

concurrency: update-app

jobs:
  update-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: champ-oss/action-update-app@main
        env:
          GITHUB_APP_ID: '${{ secrets.GH_APP_ID }}'
          GITHUB_INSTALLATION_ID: '${{ secrets.GH_INSTALLATION_ID }}'
          GITHUB_APP_PRIVATE_KEY: '${{ secrets.GH_APP_PRIVATE_KEY }}'
          GITHUB_REPO_TARGET: "example-repo"
          FILE_PATH: "test/example-01.tfvars"