name: action-update-app
description: https://github.com/champ-oss/action-update-app
inputs:
  GITHUB_APP_ID:
    description: 'github app id'
    required: true
  GITHUB_INSTALLATION_ID:
    description: 'installation id'
    required: true
  GITHUB_APP_PRIVATE_KEY:
    description: 'private key'
    required: true
  GITHUB_OWNER_TARGET:
    description: 'github owner'
    required: true
  GITHUB_REPO_TARGET:
    description: 'github repo'
    required: true
  FILE_PATH_LIST:
    description: 'file pattern list'
    required: true
  SEARCH_KEY:
    description: 'search key'
    required: false

runs:
  using: "composite"
  steps:
    - name: install jira lib
      shell: bash
      run: cd ${{github.action_path}} && pip3 install -r requirements.txt
    - name: run python script
      shell: bash
      run: |
        python3 ${GITHUB_ACTION_PATH}/action.py